### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by okor** [lksv/node-resemble.js#10]
There have been various bugfixes and improvements in the source library. It would be cool to have those updates in the node version. Thanks.

**Comment by lksv** [comment]
I would like. Unfortunately the code does not have any tests (yet). So it takes more time to me to update:(

Pull requests with tests are welcomed.

**Comment by okor** [comment]
np, totally understand. I actually ended up pivoting and using a tool called DSSIM https://github.com/pornel/dssim which you may find interesting.
