### ISSUE TITLE
exclude text while image compare

### ISSUE THREAD

**Issue by KaranbeerKaur** [lksv/node-resemble.js#32]
Hi,

How I can remove text while compare , if image has both text and image.
I want to compare only image part and don't want to highlight text.
I have attached image for reference.

![compare](https://cloud.githubusercontent.com/assets/16605677/20591804/6f1ce4e0-b250-11e6-9809-06e5c4b3db48.png)

**Comment by mirzazeyrek** [comment]
I am a little bit confused. If you need to compare images why are you capturing texts in image. What are you trying to achieve exactly ?

**Comment by KaranbeerKaur** [comment]
I want to compare images having images and text, But I want to compare images only not text. 
My query is how I can omit text compare, which settings I have to set to compare image only

**Comment by mirzazeyrek** [comment]
Is this screenshot from a web site ? If you can be more descriptive, I can suggest you better tools for this type of job.

**Comment by lksv** [comment]
Comparing "only images and not text" is out of the scope of this library.
If your texts are in particular place, you can use ignoreRectangles, see [example](https://github.com/lksv/node-resemble.js/blob/master/example/example.js#L45).

General solution would not be easy. In theory you have to employ OCR with "hOCR" results. Then you can use Hocr results as an input to the `ignoreRectangles`. For instance see [tessarect.js](https://github.com/naptha/tesseract.js) and it's `GetHOCRText` method.

**Comment by rasenplanscher** [comment]
maybe close this?

**Comment by mirzazeyrek** [comment]
Closed.
