### ISSUE TITLE
Please update Readme

### ISSUE THREAD

**Issue by sfishel18** [lksv/node-resemble.js#4]
Great library, it was exactly what I needed for a recent project!  But I ran into a few pain points due to the fact that that parts of the Readme don't seem to have been updated since forking from Resemble.js.  Specifically, what are the best practices for capturing a diff image and saving it off?  This is how I'm currently doing it, but I'm not sure if it's the best way:

```js
resemble(image1).compareTo(image2).onComplete(function(data) {
    data.getDiffImage().pack().pipe(
        fs.createWriteStream(diffImagePath)
    );
});
```

Thanks!

**Comment by SimitTomar** [comment]
Hi There,

Thanks for this library.

I tried to follow the above example but getting an empty diff image, tried the following code:

    var imgData1 = 'C:\\Users\\Image1.png';
    var imgData2 = 'C:\\Users\\Image2.png';

    var diffImage = 'C:\\Users\\';

    resemble(imgData1).compareTo(imgData2).ignoreNothing().onComplete(function (data) {

        data.getDiffImage().pack().pipe(fs.createWriteStream( diffImage + 'diff.png'));
        console.log(data);
    })

Log shows that the 2 images are different:

    { isSameDimensions: true,
      dimensionDifference: { width: 0, height: 0 },
      misMatchPercentage: '0.73',
      analysisTime: 143,
      getDiffImage: [Function] }
Not sure what am I missing here, any help would be much appreciated
