### ISSUE TITLE
Confusion about npm releases

### ISSUE THREAD

**Issue by digitaldonkey** [lksv/node-resemble.js#49]
Looking at npmjs https://www.npmjs.com/package/node-resemble-js it seems there only a release tagged with 0.2.0 available. 

In your repo I see only 1.0.1, 1.1.0, 1.1.1 tagged. 
While your fork source (https://github.com/rsmbl/Resemble.js) has tagged releases up to 3.2.4.

* Is there any plan to bublish the current releases (1.x) to npmjs? 
* are there any updated planed to match the fork source? 
* Is there any relation between your tags and the sources tags?

**Comment by benbcai** [comment]
@mirzazeyrek @lksv The master branch now pulls in pngjs@6.0.0. Can you consider releasing a new version with a dependency on pngjs@6.0.0? The latest available version (0.2.0) is using pngjs@2.2.0, which has a bug reported on https://github.com/garris/BackstopJS/issues/350. Releasing a new version would fix this issue.

**Comment by mirzazeyrek** [comment]
new package is published:

https://www.npmjs.com/package/@mirzazeyrek/node-resemble-js
