### ISSUE TITLE
How to ignore identical pixels?

### ISSUE THREAD

**Issue by shakyShane** [lksv/node-resemble.js#6]
I have a use-case where I only want the diff pixels written to the output PNG - I don't care about the ones that match.

I can remove this line https://github.com/lksv/node-resemble.js/blob/master/resemble.js#L395 and it does exactly what I want, but I was wondering if there was a config option for this?

Thanks :)

**Comment by lksv** [comment]
I am closing this issue. If it is still needed, reopen it.
