### ISSUE TITLE
Error: There are some read requests waitng on finished stream   

### ISSUE THREAD

**Issue by ShobanaV** [lksv/node-resemble.js#8]
Error: There are some read requests waitng on finished stream
  
When I compare images again and again using resemble, I am getting this error (mostly the second time or so).

**Comment by lukeapage** [comment]
This is an issue in pngjs.
If you upgrade to pngjs2 (same interface) it will fix this issue and also allow reading multiple bit depths and interlaced files.

**Comment by lksv** [comment]
Pull requests are welcome. ...and that would be really helpful.

**Comment by tommysanterre** [comment]
I still have the same error

**Comment by lukeapage** [comment]
did you test the repo? a new version has not been published.

**Comment by tommysanterre** [comment]
Yes i did. I think it happens when we start writing a diff image while
there is another one being written.

**Comment by lukeapage** [comment]
do you have a repo I can reproduce this error with?

**Comment by tommysanterre** [comment]
My repo was a bit too complex, I tried to simplify it as much as possible.

https://github.com/tommysanterre/reproduce-node-resemble.js-issue-8

**Comment by tommysanterre** [comment]
The error was in my code. When writing the screenshots I was taking I was not waiting for the stream to finish writing.

**Comment by lukeapage** [comment]
Thanks, saved me some time investigating.
Note: There was a case where pngjs caused this error that was fixed, just looks like it may not have been the problem in your case.
